services:
  plutonium-key-generator:
    build: .
    environment:
      - BASE_URL=https://platform.plutonium.pw/serverkeys/
      - COOKIE={PLUTONIUM_COOKIE}
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"